name: aws-nuke-run

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run_aws_nuke:
    name: Run aws-nuke
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_TEST }}
          aws-region: ap-northeast-1

      - name: Run aws-nuke
        run: docker compose run aws-nuke --no-dry-run